### PR TITLE
near login: do not open webpage automatically on linux

### PR DESCRIPTION
**Pull request by mikedotexe**
Workaround for issue described here: https://github.com/near/near-shell/issues/358

### CODE REVIEW

**Comment by mikedotexe** [comment]
@vgrichina I can't find it right now, but I remember we both saw a community member using Ubuntu see this errant behavior even with the change using 302 instead of 301.

**Comment by vgrichina** [comment]
@mikedotexe I don't think we should disable it for everyone on Linux if it happens only in some edge case (i.e. we cannot reproduce ourselves on stock Ubuntu, etc).

Maybe that user just had their Chrome still keep the cache from attempt with unfixed version (most likely explanation). If it happens again we should direct user to clear the cache and see if it helps.

**Comment by mikedotexe** [comment]
> @mikedotexe I don't think we should disable it for everyone on Linux if it happens only in some edge case (i.e. we cannot reproduce ourselves on stock Ubuntu, etc).
> 
> Maybe that user just had their Chrome still keep the cache from attempt with unfixed version (most likely explanation). If it happens again we should direct user to clear the cache and see if it helps.

I disagree. We have consistently heard from people (at least 5-6 in one week) that this is happening. People can click on the link in the command line. We've introduced a bug in the feature that automatically opens a tab. Let's remove that buggy feature and unblock our developers/stakers.

**Comment by vgrichina** [comment]
@mikedotexe there is no plausible explanation for this happening besides Chrome still using old cached URL (because of 301 being used earlier). It's not like wrong link can be opened because of some magical reason.

**Comment by mikedotexe** [comment]
Okay, I guess I'll (re)close this according to the last comment and since we haven't heard of this happening for a couple weeks.

**Pull request closed without merging**
